# Generated by Django 5.1.2 on 2025-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcart',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
