# Generated by Django 5.1.2 on 2024-12-16 16:06

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='food',
            name='available_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='available_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='serve_period',
            field=models.CharField(blank=True, choices=[('Sáng', 'Morning'), ('Trưa', 'Noon'), ('Chiều', 'Afternoon'), ('Tối', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='star_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(related_name='following_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='danh mục chính'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(default=5)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to='app.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='app.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
