# Generated by Django 5.1.2 on 2025-02-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_comment_review_customer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcategory',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
    ]
