# Generated by Django 5.1.2 on 2025-01-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurantaddress_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantaddress',
            old_name='stress',
            new_name='street',
        ),
    ]
