# Generated by Django 5.1.2 on 2025-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcart_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myaddress',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
