# Generated by Django 5.1.2 on 2025-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restaurantcategory_confirmation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantcategory',
            name='confirmation_status',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
    ]
