# Generated by Django 5.1.2 on 2025-01-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myaddress_phone_number_myaddress_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
