# Generated by Django 5.1.2 on 2025-01-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_stress_restaurantaddress_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='street',
        ),
    ]
