# Generated by Django 5.1.2 on 2025-01-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myaddress_latitude_myaddress_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaddress',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='myaddress',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
