# Generated by Django 5.1.2 on 2024-12-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_menu_myaddress_order_orderdetail_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(related_name='menu_food', to='app.food'),
        ),
    ]
