# Generated by Django 5.1.2 on 2025-01-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_restaurantaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantaddress',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurantaddress',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
