# Generated by Django 5.1.2 on 2025-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='shipping_fee',
            field=models.FloatField(null=True),
        ),
    ]
